USE music_streaming;

INSERT INTO realtime_plays
(user_id, timestamp, song, artist, session_id, duration)
VALUES
('user_1', '2024-01-01 10:30:00', 'Blinding Lights', 'The Weeknd', 'session_1', 245);

INSERT INTO realtime_plays
(user_id, timestamp, song, artist, session_id, duration)
VALUES
('user_2', '2024-01-01 11:15:00', 'Shape of You', 'Ed Sheeran', 'session_2', 233);

INSERT INTO realtime_plays
(user_id, timestamp, song, artist, session_id, duration)
VALUES
('user_3', '2024-01-01 12:20:00', 'Believer', 'Imagine Dragons', 'session_3', 204);

INSERT INTO realtime_plays
(user_id, timestamp, song, artist, session_id, duration)
VALUES
('user_1', '2024-01-01 13:10:00', 'Perfect', 'Ed Sheeran', 'session_4', 263);

INSERT INTO realtime_plays
(user_id, timestamp, song, artist, session_id, duration)
VALUES
('user_4', '2024-01-01 14:25:00', 'Havana', 'Camila Cabello', 'session_5', 217);
